spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database: mysql
    hibernate:
    ddl-auto: update
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  profiles:
    include: oauth, database, mail

server:
  port: 8080

google:
  api:
    calendar:
      url: https://www.googleapis.com/calendar/v3

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql : trace